<a href="https://colab.research.google.com/github/sampathsoora/Retail_EDA/blob/main/Module2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy's Structured Arrays

In [1]:
import numpy as np

In [6]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]
name
age
weight

[55.0, 85.5, 68.0, 61.5]

In [5]:
x = np.zeros(4, dtype=int)
x

array([0, 0, 0, 0])

In [4]:
# Use a compound data type for structured arrays
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [7]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [8]:
# Get all names
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [9]:
# Get first row of data
data[0]

('Alice', 25, 55.)

In [10]:
# Get the name from the last row
data[-1]['name']

'Doug'

In [11]:
# Get names where age is under 30
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

# Creating Structured Arrays

In [12]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [13]:
np.dtype({'names':('name', 'age', 'weight'),
          'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [14]:

np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [15]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [16]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [18]:
data['age']

array([25, 45, 37, 19], dtype=int32)

In [19]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age

The slowest run took 47.82 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 209 ns per loop
The slowest run took 12.85 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.96 µs per loop
The slowest run took 8.32 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 3.82 µs per loop
