<a href="https://colab.research.google.com/github/sampathsoora/Retail_EDA/blob/main/Module2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importing a module

In [1]:
import math

x = 2
y1 = math.exp(x)
y2 = math.log(x)

print("e^{} is {} and log({}) is {}".format(x, y1, x, y2))

e^2 is 7.38905609893065 and log(2) is 0.6931471805599453


In [2]:
from math import exp

x = 2
y = exp(x)  # no need to math.exp()

print("e^{} is {}".format(x, y))

e^2 is 7.38905609893065


In [3]:
# you can change the name of the imported object
from math import exp as myfun

x = 2
y = myfun(x)

print("e^{} is {}".format(x, y))

e^2 is 7.38905609893065


In [4]:
from math import *

x = 2
y1 = exp(x)
y2 = log(x)

print("e^{} is {} and log({}) is {}".format(x, y1, x, y2))

e^2 is 7.38905609893065 and log(2) is 0.6931471805599453


In [6]:
import math
n = 10
# factorial means that the result when you multiply a whole number by all the numbers below it
# Hence, factorial(n) = n * (n-1) * (n-2) * ...... * 1
print(math.factorial(n))

3628800


In [7]:
def my_factorial(n):
    if n==1:
        return 1
    else:
        return n * my_factorial(n-1)    
print(my_factorial(10))

3628800


# Python Simple I/O

In [8]:
x = input('What is your name? ')

print("x is {}".format(type(x)))
print("Your name is {}".format(x))

What is your name? Soora
x is <class 'str'>
Your name is Soora


In [10]:
x = input('Enter a real number between -1 and 1: ')
y = math.acos(float(x))
# acos function is used as the trigonometric function that is equal to the ratio of the side adjacent to an acute angle (in a right-angled triangle) to the hypotenuse.
print('acos({}) = {}'.format(x,y))

Enter a real number between -1 and 1: 0.98
acos(0.98) = 0.20033484232311968


In [12]:
# Add if-else statement on the exercise 3
x = input('Enter a real number between -1 and 1: ')
x = float(x)
if x>=-1 and x<=1:
    y = math.acos(x)
    print('acos({}) = {}'.format(x,y))
else:
    print('Out of range')

Enter a real number between -1 and 1: 2
Out of range


In [13]:
name = "John"
msg = "Hello"

print(msg)
print(msg, name)

Hello
Hello John


In [14]:
print('Sample is using the end=\'\,\'')
for i in range(10):
    print(i, end=',')    
print('\nSample is using the end=\' \'')   
for i in range(10):    
    print(i, end=' ')
print('\nSample is without the end arguments') 
for i in range(10):    
    print(i)

Sample is using the end='\,'
0,1,2,3,4,5,6,7,8,9,
Sample is using the end=' '
0 1 2 3 4 5 6 7 8 9 
Sample is without the end arguments
0
1
2
3
4
5
6
7
8
9


# DateTime Module

In [15]:

import datetime

t = datetime.time(11, 21, 33)
print(t)
print('hour  :', t.hour)
print('minute:', t.minute)
print('second:', t.second)
print('microsecond:', t.microsecond)
print('tzinfo:', t.tzinfo)

11:21:33
hour  : 11
minute: 21
second: 33
microsecond: 0
tzinfo: None


In [16]:
import datetime

today = datetime.date.today()
print(today)
print('ctime:', today.ctime())
print('tuple:', today.timetuple())
print('ordinal:', today.toordinal())
print('Year:', today.year)
print('Mon :', today.month)
print('Day :', today.day)

2021-04-07
ctime: Wed Apr  7 00:00:00 2021
tuple: time.struct_time(tm_year=2021, tm_mon=4, tm_mday=7, tm_hour=0, tm_min=0, tm_sec=0, tm_wday=2, tm_yday=97, tm_isdst=-1)
ordinal: 737887
Year: 2021
Mon : 4
Day : 7


In [17]:
import datetime

d1 = datetime.date(2013, 3, 12)
print('d1:', d1)

d2 = d1.replace(year=2015)
print('d2:', d2)

d1: 2013-03-12
d2: 2015-03-12


In [19]:
import datetime
day_of_week = {0 : 'Monday',
              1: 'Tuesday',
              2: 'Wednesday',
              3: 'Thursday',
              4: 'Friday',
              5: 'Saturday',
              6: 'Sunday'}
# you could also use a list to store the days o the week
# and it would work just fine.
# days_of_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

print('Today is', day_of_week[datetime.date.today().weekday()])

# Assume my birthday value is 10/10/2008
my_birthdate = datetime.date(2008,7,9)
print('I was born on', day_of_week[my_birthdate.weekday()])

# Change the previous birthday year value with 2019
t2 = my_birthdate.replace(year=2019)
print('and my birthday this year is on a', day_of_week[t2.weekday()])

Today is Wednesday
I was born on Wednesday
and my birthday this year is on a Tuesday


In [20]:
today = datetime.datetime.today()
print(today)

tomorrow = today + datetime.timedelta(days=1)  
print(tomorrow)

2021-04-07 18:41:43.475764
2021-04-08 18:41:43.475764


In [21]:
import datetime
day_of_week = {0 : 'Monday',
              1: 'Tuesday',
              2: 'Wednesday',
              3: 'Thursday',
              4: 'Friday',
              5: 'Saturday',
              6: 'Sunday'}
# You could also use a list to store the days o the week
# and it would work just fine.
# days_of_week = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

print('Today is', day_of_week[datetime.date.today().weekday()])

# Assume my birthday value is 10/10/2008
my_birthdate = datetime.date(2008,10,10)
print('I was born on', day_of_week[my_birthdate.weekday()])

# Change the previous birthday year value with 2019
#You need to note that both 2012 and 2016 are leap year, which are 366 days in one year not 365 days.
t2 = my_birthdate + datetime.timedelta(days=365)*9 + datetime.timedelta(days=366)*2
print('and my birthday this year is on a', day_of_week[t2.weekday()])

Today is Wednesday
I was born on Friday
and my birthday this year is on a Thursday


In [22]:
today = datetime.datetime.today()
print('ISO     :', today)

ISO     : 2021-04-07 18:47:43.969387


In [23]:
str_format = "%a %b %d %H:%M:%S %Y"
s = today.strftime(str_format)
print('strftime:', s)

strftime: Wed Apr 07 18:47:43 2021


In [25]:
print(s)

d = datetime.datetime.strptime(s, str_format)
print(d)
print('strptime:', d.strftime(str_format))

Wed Apr 07 18:47:43 2021
2021-04-07 18:47:43
strptime: Wed Apr 07 18:47:43 2021


In [26]:
# Define a string variable "s", its value is 07/03/2017
s = "07/03/2017"
# Define the string format
str_format = "%m/%d/%Y"


d = datetime.datetime.strptime(s, str_format)
print(d)

2017-07-03 00:00:00


In [27]:
s = '7/30/2017 - 12:13'
str_format = "%m/%d/%Y - %H:%M"
t = datetime.datetime.strptime(s, str_format)
print(t)

2017-07-30 12:13:00


# Numpy Module

In [32]:
import numpy as np

In [29]:
x = [1, 7, 3, 4, 0, -5]
print(x)

[1, 7, 3, 4, 0, -5]


In [33]:
y = np.array(x)
type(y)

numpy.ndarray

In [34]:
range(5)

range(0, 5)

In [35]:
print(np.array(range(5)))

[0 1 2 3 4]


In [36]:
print(np.arange(2, 3, 0.2))  # Why is there no value 3.0 in the output?

[2.  2.2 2.4 2.6 2.8]


In [42]:
print(np.linspace(2, 3, 5))    # returns numbers spaced evenly on a linear scale, both endspoints are included

[2.   2.25 2.5  2.75 3.  ]


In [38]:
print(np.logspace(2, 3, 5))   # returns numbers spaced evenly on a log scale

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


In [43]:
np.logspace?

In [44]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [45]:
print("The 1st sample is",np.ones(5, dtype=int))   # you can specify the data type, default is float
print("The 2nd sample is ",np.ones(5, dtype=float)) 
print("The 3rd sample is ",np.ones((5,5), dtype=int)) 
print("The 4th sample is ",np.ones((5,5,5), dtype=int))

The 1st sample is [1 1 1 1 1]
The 2nd sample is  [1. 1. 1. 1. 1.]
The 3rd sample is  [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
The 4th sample is  [[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [48]:
np.ones? # You can use this command to learn what is the function of np.ones

SyntaxError: ignored

In [49]:
x, y = np.mgrid[0:5, 0:3]

print(x)
print(y)

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]


In [50]:
np.mgrid?

In [51]:
y = np.array([3, 0, -4, 6, 12, 2])

In [52]:
print("number of dimensions:\t", y.ndim)        
print("dimension of the array:", y.shape)       
print("numerical data type:\t", y.dtype)
print("maximum of the array:\t", y.max())       
print("index of the array max:", y.argmax())    
print("mean of the array:\t", y.mean())

number of dimensions:	 1
dimension of the array: (6,)
numerical data type:	 int64
maximum of the array:	 12
index of the array max: 4
mean of the array:	 3.1666666666666665


In [53]:
x = [[1, 2, 10, 20], [3, 4, 30, 40]]
y = np.array(x)
print(y)
print()
print(y.ndim, y.shape)

[[ 1  2 10 20]
 [ 3  4 30 40]]

2 (2, 4)


In [54]:
x = np.ones((3, 5), dtype='int')

In [55]:
print(x)
print()
print(x.ndim, x.shape)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

2 (3, 5)


In [56]:
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [57]:
x = np.array([2, 8, -2, 4, 3])
print(x[3])

4


In [59]:
x = np.array([[7, 6, 8, 6, 4],
              [4, 7, -2, 0, 9]])
              
print(x[1, 3])

0


In [60]:
print(x[1, :])      # or x[1]

[ 4  7 -2  0  9]


In [61]:
print(x[:, 3])

[6 0]


In [62]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

idx1 = [1, 3, 4]        # list
idx2 = np.array(idx1)   # array

print(x[idx1], x[idx2])
x[idx2] = 0
print(x)

[8 4 3] [8 4 3]
[ 2  0 -2  0  0  9  0]


In [63]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

In [64]:
mask = np.array([False, True, True, False, False, True, False])

In [65]:
x[mask]

array([ 8, -2,  9])

In [66]:
x = np.array([2, 8, -2, 4, 3, 9, 0])
mask = (x>=2) * (x<9)
x[mask]

array([2, 8, 4, 3])

In [67]:
x = np.array([2, 8, -2, 4, 3, 9, 0])

print(x[3:])    # slicing
print(x[3:7:2])  # slicing with a specified step

[4 3 9 0]
[4 9]


In [68]:
x = np.array([[7, 6, 8, 6, 4, 3],
              [4, 7, 0, 5, 9, 5],
              [7, 3, 6, 3, 5, 1]])
              

print(x[1, 1:4])
print()
print(x[:2, 1::2])    # rows zero up to 2, cols 1 up to end with a step=2

[7 0 5]

[[6 6 3]
 [7 5 5]]


In [69]:
a = np.arange(0, 50, 7)
print(a)
for item in a:
    print(item,)

[ 0  7 14 21 28 35 42 49]
0
7
14
21
28
35
42
49


In [70]:
a = np.arange(0, 50, 7)
for i in range(a.shape[0]):
    print(a[i],)

0
7
14
21
28
35
42
49


In [71]:
x = [1, 2, 3]
y = x
print(x, y)

[1, 2, 3] [1, 2, 3]


In [72]:
y[0] = 0       # now we alter an element of y
print(x, y)     # note that x has changed as well

[0, 2, 3] [0, 2, 3]


In [73]:
x = np.array([1, 2, 3])
y = x

y[0] = 0       # now we alter an element of y
print(x, y)     # note that x has changed as well

[0 2 3] [0 2 3]


In [74]:
x = np.array([1, 2, 3])
y = x.copy()  # or np.copy(x)
y[0] = 0

print(x, y)

[1 2 3] [0 2 3]


In [75]:
x1 = np.arange(6)
x2 = x1.reshape((2, 3))    # or np.reshape(x1, (2, 3))

print(x1)
print()
print(x2)

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]


In [76]:
x1 = np.arange(5)
x2 = x1.astype(float)

print(type(x1), x1)
print(type(x2), x2)

<class 'numpy.ndarray'> [0 1 2 3 4]
<class 'numpy.ndarray'> [0. 1. 2. 3. 4.]


In [77]:
x1 = np.random.randint(5, size=(2, 4))
x2 = x1.T

print(x1)
print()
print(x2)

[[4 1 1 1]
 [4 2 4 4]]

[[4 4]
 [1 2]
 [1 4]
 [1 4]]


In [78]:
x1 = np.array([[2, 3, 5, 7], 
               [2, 4, 6, 8]], dtype=float)
x2 = np.array([[6, 5, 4, 3], 
               [9, 7, 5, 3]], dtype=float)

In [79]:
print(x1)
print()
print(x2)

[[2. 3. 5. 7.]
 [2. 4. 6. 8.]]

[[6. 5. 4. 3.]
 [9. 7. 5. 3.]]


In [80]:
print(x1 + x2)

[[ 8.  8.  9. 10.]
 [11. 11. 11. 11.]]


In [81]:
print(x1 - x2)

[[-4. -2.  1.  4.]
 [-7. -3.  1.  5.]]


In [82]:
print(x1 * x2)

[[12. 15. 20. 21.]
 [18. 28. 30. 24.]]


In [83]:
print(x1 / x2)

[[0.33333333 0.6        1.25       2.33333333]
 [0.22222222 0.57142857 1.2        2.66666667]]


In [84]:
print(3 + x1)

[[ 5.  6.  8. 10.]
 [ 5.  7.  9. 11.]]


In [85]:
print(3 * x1)

[[ 6.  9. 15. 21.]
 [ 6. 12. 18. 24.]]


In [86]:
print(3 / x1)

[[1.5        1.         0.6        0.42857143]
 [1.5        0.75       0.5        0.375     ]]


In [87]:
x1 = np.array([2, 3, 5, 7])
x2 = np.array([2, 4, 6, 7])
y = x1<x2

print( y, y.dtype)

[False  True  True False] bool


In [88]:
print (y.all())
print (y.any())

False
True


In [89]:
print( np.random.rand())

0.8726584611284698


In [90]:
# 2x5 random array drawn from standard normal distribution
print( np.random.random([2, 5]))

[[0.57290148 0.53653892 0.60125521 0.57190328 0.54515206]
 [0.07347023 0.61003739 0.08543369 0.4222546  0.09071287]]


In [91]:
# 2x5 random array drawn from standard normal distribution
print (np.random.rand(2, 5))

[[0.37817096 0.03116489 0.31140673 0.10619673 0.17503182]
 [0.39064332 0.94881031 0.14797486 0.95580852 0.86656501]]


In [92]:
# 2x5 random array drawn from a uniform distribution on {0, 1, 2, ..., 9}
print (np.random.randint(10, size=[2, 5]))

[[2 8 5 3 8]
 [7 8 8 1 1]]


In [93]:
for i in range(5):
    print (np.random.random(),)

0.5460911366456651
0.31088480114301564
0.581082648972037
0.7900992298629113
0.18849893752821767


In [94]:
for i in range(5):
    np.random.seed(100)
    print (np.random.random(),)

0.5434049417909654
0.5434049417909654
0.5434049417909654
0.5434049417909654
0.5434049417909654


In [96]:
def step_func(x):
    """
    scalar implementation of step function
    """
    
    if x>=0:
        return 1
    else:
        return 0

In [100]:
# since step_func expects a scalar and recieves an array instead, 
# it raises an error
step_func(np.array([2, 7, -4, -9, 0, 4]))

ValueError: ignored

In [99]:
step_func_vectorized = np.vectorize(step_func)
step_func_vectorized(np.array([2, 7, -4, -9, 0, 4]))

array([1, 1, 0, 0, 1, 1])

In [101]:
def step_func2(x):
    """
    vector and scalar implementation of step function
    """
    
    return 1 * (x>=0)

In [102]:
step_func2(np.array([2, 7, -4, -9, 0, 4]))

array([1, 1, 0, 0, 1, 1])

# File I/O

In [104]:
!pip install wget

  Created wheel for wget: filename=wget-3.2-cp37-none-any.whl size=9681 sha256=412ea44be5da19a94800b6b3283014ea365fab86d5adbe8347e1f44999706e48
  Stored in directory: /root/.cache/pip/wheels/40/15/30/7d8f7cea2902b4db79e3fea550d7d7b85ecb27ef992b618f3f
Successfully built wget


In [105]:
import wget

link_to_data = 'https://github.com/tulip-lab/sit742/raw/master/Jupyter/data/csv_data1.csv'
DataSet = wget.download(link_to_data)

In [106]:
import numpy as np

# This code is for local PC
# x = np.loadtxt("data/txt_data1.txt")

# The following code for IBM Cloud
link_to_data = 'https://github.com/tulip-lab/sit742/raw/master/Jupyter/data/txt_data1.txt'
DataSet = wget.download(link_to_data)

x = np.loadtxt("txt_data1.txt")
x

array([ 2. ,  4.5,  2. ,  0. , -2. ])

In [107]:
y = np.random.randint(10, size=5)
np.savetxt("txt_data2.txt", y)
y

array([3, 7, 7, 0, 4])

In [108]:
import wget

link_to_data = 'https://github.com/tulip-lab/sit742/raw/master/Jupyter/data/csv_data1.csv'
DataSet = wget.download(link_to_data)

print(DataSet)

csv_data1 (1).csv


In [109]:
import numpy as np


x = np.genfromtxt("csv_data1.csv", delimiter=",")
x

array([[5., 8., 9., 0.],
       [0., 4., 6., 5.],
       [9., 9., 5., 2.],
       [0., 8., 3., 6.],
       [7., 9., 8., 6.],
       [1., 1., 5., 3.]])

In [110]:
x = np.random.randint(10, size=(6,4))
np.savetxt("csv_data2.csv", x, delimiter=',')
x

array([[2, 5, 2, 2],
       [2, 1, 0, 8],
       [4, 0, 9, 6],
       [2, 4, 1, 5],
       [3, 4, 4, 3],
       [7, 1, 1, 7]])

In [111]:
link_to_data = 'https://github.com/tulip-lab/sit742/raw/master/Jupyter/data/json_data1.json'
DataSet = wget.download(link_to_data)

print(DataSet)

json_data1.json


In [112]:
import json
with open("json_data1.json", 'rb') as fp:
    fcontent = fp.read()
# data = json.loads(fcontent)
data = json.loads(fcontent.decode('utf-8'))
data.keys()

dict_keys(['firstName', 'lastName', 'isAlive', 'age', 'address', 'phoneNumbers', 'children', 'spouse'])

In [113]:
data

{'address': {'city': 'New York',
  'postalCode': '10021-3100',
  'state': 'NY',
  'streetAddress': '21 2nd Street'},
 'age': 25,
 'children': [],
 'firstName': 'John',
 'isAlive': True,
 'lastName': 'Smith',
 'phoneNumbers': [{'number': '212 555-1234', 'type': 'home'},
  {'number': '646 555-4567', 'type': 'office'}],
 'spouse': None}

In [114]:
data['phoneNumbers']

[{'number': '212 555-1234', 'type': 'home'},
 {'number': '646 555-4567', 'type': 'office'}]

In [115]:
data = [{'Name': 'Zara', 'Age': 7, 'Class': 'First'}, 
        {'Name': 'Lily', 'Age': 9, 'Class': 'Third'}];
data

[{'Age': 7, 'Class': 'First', 'Name': 'Zara'},
 {'Age': 9, 'Class': 'Third', 'Name': 'Lily'}]

In [117]:
with open("json_data_now.json", 'w') as fp:
    json.dump(data, fp)